formPrac/form/urls.py
from django.conf.urls import url
from . import views

<<<<<<< HEAD
app_name = 'form'
=======

>>>>>>> bb980a8d69038e69ac8eb1831811fe1bb3ecae27
urlpatterns = [

    url(r'^$', views.get_Name, name='get_Name'),


]

formPrac/formPrac/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
<<<<<<< HEAD
    url(r'^user/', include('user.urls')),
    url(r'^formTwo/', include('formTwo.urls')),
=======
>>>>>>> bb980a8d69038e69ac8eb1831811fe1bb3ecae27
    url(r'^form/', include('form.urls')),
    url(r'^admin/', admin.site.urls),
]

formPrac/formTwo/urls.py
from django.conf.urls import url
from . import views

app_name = 'formTwo'

urlpatterns = [

    url(r'^$', views.get_name, name='get_name' ),
]

formPrac/user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'

urlpatterns = [

    url(r'^$', views.login, name='login'),

    url(r'^signup/$', views.signup, name='signup'),


]

formPrac/form/models.py
from django.db import models

# Create your models here.

formPrac/formTwo/models.py
from django.db import models

# Create your models here.

formPrac/user/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=15)
    password = models.CharField(max_length=12)

    def __str__(self):
        return self.username

'''
class Details(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile_no = models.IntegerField()
    

'''

formPrac/form/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='your name', max_length=100)
<<<<<<< HEAD




=======
>>>>>>> bb980a8d69038e69ac8eb1831811fe1bb3ecae27
    

formPrac/formTwo/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

formPrac/user/forms.py
# from django import forms


# class Login(forms.Form):

formPrac/form/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .forms import NameForm

def get_Name(request):

    if request.method == 'POST':
        form = NameForm(request.POST)

        if form.is_valid():
            return HttpResponseRedirect('/thanks/')

    else:
        form = NameForm()

    return render(request, 'form/name.html', {'form': form})

formPrac/formTwo/views.py
<<<<<<< HEAD
from django.core.mail import send_mail
from .forms import ContactForm
from django.http import HttpResponseRedirect
from django.shortcuts import render

def get_name(request):

    if request.method=='POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['yasir.choudhary@fafadiatech.com']

            if cc_myself:
                recipients.append(sender)

            send_mail(subject, message, sender, recipients)

            return HttpResponseRedirect('/thanks/')
    else:
        form = ContactForm()

    return render(request, 'formTwo/sendMail.html', {'form':form})


=======
from django.shortcuts import render

# Create your views here.
>>>>>>> bb980a8d69038e69ac8eb1831811fe1bb3ecae27

formPrac/user/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from .models import User


def login(request):
    if request.method == 'POST':
        try:
            user = User.objects.get(username=request.POST['username'])
        except User.DoesNotExist:
            return HttpResponse("This username doen't exist")
        else:
            if user.password == request.POST['password']:
                request.session['id_user'] = user.id
                return render(request, 'user/home.html', {'user': user})

            else:
                return HttpResponse("your username and password didn't match")
    else:

        return render(request, 'user/login.html')



def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = User(username=username, password=password)
        user.save()

        return render(request, 'user/redirect.html')
    else:
        return render(request, 'user/signup.html')


    '''
    IMP Links
    https://docs.djangoproject.com/en/2.0/topics/http/sessions/
    
    
    '''

formPrac/form/templates/form/name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Form</title>
</head>
<body>

<<<<<<< HEAD
    <form action="{% url 'form:get_Name' %}" method="post">
=======
    <form action="{% url 'get_Name' %}" method="post">
>>>>>>> bb980a8d69038e69ac8eb1831811fe1bb3ecae27

        {% csrf_token %}

        {{ form }}
        <!--
        <label for="your_name">your name</label>
        <input type="text" id="your_name" name="your_name" value="{{ current_name }}">
        -->
        <br/>
        <input type="submit" value="Submit">
    </form>

</body>
</html>

formPrac/formTwo/templates/formTwo/sendMail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Send Mail</title>
</head>
<body>

    <form action="{% url 'formTwo:get_name' %}" method="post">
        {% csrf_token %}

        <!-- {{ form.as_p }} -->


         <p>
            <label for="id_subject">Subject:</label>
            <input id="id_subject" type="text" name="subject" maxlength="1000" required/>
        </p>

        <p>
            <label for="id_message">Message:</label>
            <textarea id="id_message" name="message" required></textarea>
        </p>
        <p>
            <label for="id_sender">Sender:</label>
            <input type="email" name="sender" id="id_sender" required/>
        </p>
        <p>
            <label for="id_cc_myself">Cc_myself:</label>
            <input type="checkbox" name="cc_myself" id="id_cc_myself" />
        </p>


        <input type="Submit" value="Send">

    </form>

</body>
</html>

formPrac/user/templates/user/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>

<h1>WELCOME {{user.username}} To mysite</h1>

</body>
</html>

formPrac/user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>

    <form action="{% url 'user:login' %}" method="post">
    {% csrf_token %}
    <h2>Login</h2>
    <label for="id_user">UserName</label>
    <input type="text" name="username" id="id_user" minlength="5" maxlength="15" required/><br/>
        <br/>
    <label for="id_password">Password</label>
    <input type="password" name="password" id="id_password" minlength="6" maxlength="12" required/></br>

    <input type="submit" value="Login">

        <a href="{% url 'user:signup' %}">Sign Up</a>

    </form>


</body>
</html>

formPrac/user/templates/user/redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Successfully</title>
</head>
<body>



<h1>You have succesfully created an account now you can login</h1>

<a href="{% url 'user:login' %}">Go to Login Page</a>

</body>
</html>

formPrac/user/templates/user/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up</title>
</head>
<body>

    <form action="{% url 'user:signup' %}" method="post">

        {% csrf_token %}

        <label for="id_user">Username</label>
        <input type="text" name="username" id="id_user" required/><br/>
        <br>
        <label for="id_password">Password</label>
        <input type="password" name="password" id="id_password" required>

        <input type="submit" value="Register">



    </form>


</body>
</html>