webApp/music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'

urlpatterns =[
    #/music
    url(r'^$', views.IndexView.as_view(), name='index'),


    #music/register
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #/music/11
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # album_id replaced with pk

    #/music/album/add/
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    #/music/album/2/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    #/music/album/add/
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

]

webApp/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^music/', include('music.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

webApp/music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=210)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return ("artist={} , album_title={}".format(self.artist,self.album_title))

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE )
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return ("songtitle = {}".format(self.song_title))

webApp/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

webApp/music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login
from django.shortcuts import render,redirect
from django.views.generic import View
from django.views import generic
from .models import Album
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    # template_name = album_form
    # context = form

    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # if user wants to change the password
            user.set_password(password)
            user.save()

            # returns user objects if credential are correct
            user = authenticate(username=username, password=password)


            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')


        return render(request, self.template_name, {'form': form})

webApp/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add New Title{% endblock %}

{% block body %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
        <div>
            <span>{{ field.errors }}</span>
        </div>
        <label>{{ field.label_tag }}</label>
        <div> {{ field }} </div>

        {% endfor %}

        <!-- Here action is none -->


        <button type="submit" class="btn btn-success">Submit</button>

    </form>

{% endblock %}

webApp/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>{% block title %}Viber{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=PT+Serif|Satisfy" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viber</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="query" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <spna class="glyphicon glyphicon-plus" aria-hidden="true"></spna>&nbsp; Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <spna class="glyphicon glyphicon-off" aria-hidden="true"></spna>&nbsp; Logout
                    </a>
                </li>

            </ul>

        </div>

    </div>
</nav>

{% block body %}
{% endblock %}


</body>
</html>

webApp/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}AlbumDetails{% endblock %}

{% block body %}

    <img src="{{ album.album_logo.url }}">
    <h2>{{ album.album_title }}</h2>
    <h3>{{ album.artist }}</h3>

        {% for song in album.song_set.all %}
            {{ song.song_title }}
        {% endfor %}
    <br>

    <a href="{% url 'music:album-update' album.id %}">Update</a>

    <form action="{% url 'music:album-delete' album.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>

{% endblock %}

webApp/music/templates/music/form-template.html
{% for field in form %}
    <div>
        <span>{{ field.errors }}</span>
    </div>
    <label>{{ field.label_tag }}</label>
    <div> {{ field }} </div>

{% endfor %}

webApp/music/templates/music/index.html
{% extends 'music/base.html' %}


{% block body %}

    <ul>
        <!-- object_list = album_list -->
        {% for album in all_albums %}
            <li><a href="{% url 'music:detail' album.id %}">{{album.album_title}}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}

webApp/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Create New Account{% endblock %}


{% block body %}

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}

        {% for field in form %}
            <div>
                <span>{{ field.errors }}</span>
            </div>
            <label>{{ field.label_tag }}</label>
            <div>{{ field}}</div>
        {% endfor %}

        <button type="submit" class="btn btn-success">Submit</button>

    </form>

{% endblock %}