webProj/todo/urls.py
from django.conf.urls import url
from . import views

app_name = 'todo'

urlpatterns = [

    #url(r'^$', views.start, name='start'),

    #url(r'^index/', views.index, name='index'),

     url(r'^$', views.login, name='login'),
    #url(r'^login/', views.login, name='login'),

    url(r'^addtask/$', views.addtask, name='addtask'),

   # url(r'^login/', views.login, name='login'),

    url(r'^signup/', views.signup, name='signup'),

    url(r'^(?P<id>[0-9]+)/$', views.delete, name='delete'),

    url(r'(?P<id>[0-9]+)/edit/$', views.edit, name='edit'),

    #url(r'(?P<id>[0-9]+)/update/$', views.UpdateView.as_view(), name='update')


    # url(r'^/addtask/added/$', views.added, name='added')
]

webProj/webProj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    #url(r'^$', include('todo.urls')),
    url(r'^todo/', include('todo.urls')),
    url(r'^admin/', admin.site.urls),
]

webProj/todo/models.py
from django.db import models



class User(models.Model):
    username = models.CharField(max_length=15)
    password = models.CharField(max_length=12)

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_text = models.CharField(max_length=250)
    due_date = models.DateField()

    def __str__(self):
        return "{} , {}".format(self.task_text,self.due_date)

webProj/todo/forms.py
from django import forms

class TaskForm(forms.Form):
    task_text = forms.CharField(max_length=250)
    due_date = forms.DateField()

webProj/todo/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, HttpResponse
from .models import User, Task
from .forms import TaskForm
from django.views.generic.edit import UpdateView


'''
def index(request):
    tasks_list = Task.objects.all()
    if tasks_list:  
        context = { 'tasks_list': tasks_list }
        return render(request, 'todo/index.html', context)
    else:
        tasks_empty_list = Task()
        context = {'tasks_empty_list': tasks_empty_list}
        return render(request, 'todo/index.html', context)

'''

user_id = 0

def login(request):
    if request.method == 'POST':
        try:
            user = User.objects.get(username=request.POST['username'])
        except User.DoesNotExist:
            return HttpResponse("Username is invalid")
        else:
            if user.password == request.POST['password']:
                try:
                    #tasks_list = Task.objects.get(user=user)
                    #print(tasks_list)
                    tasks_list = user.task_set.all()
                    global user_id
                    user_id = user.id

                except Task.DoesNotExist:
                    #return HttpResponse("Task doesn't exist ")
                    pass
                    '''
                    task_list = Task()
                    user_id = user.id
                    username = user.username
                    context = {'task_list': task_list,
                                'user_id' : user_id,
                               'username' : username
                               }
                    return render(request, 'todo/index.html', context)
                    
                    
                    '''

                else:
                    context = {'tasks_list': tasks_list,
                               'username': user.username,
                               }
                    return render(request, 'todo/index.html', context)

            else:
                return HttpResponse("Your Password is in correct ")



    else:
        return render(request, 'todo/login.html')

def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User(username=username, password=password)
        user.save()

        return render(request, 'todo/redirect.html')

    else:
        return render(request, 'todo/signup.html')


def addtask(request):
    if request.method=='POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            #logged_user = request.user
            #user_id = logged_user.id

            global user_id

            task_text = request.POST.get('task_text')
            due_date = request.POST.get('due_date')

            task = Task(user_id=user_id ,task_text = task_text, due_date = due_date )
            task.save()

            #context = {}
            user = User.objects.get(id=user_id)
            tasks_list= user.task_set.all()

            context = {
                'tasks_list' : tasks_list,
                'username' : user.username,
            }


            #return HttpResponseRedirect(reverse(request,'todo:index'))
            return render(request, 'todo/index.html', context)

    else:
        form = TaskForm()

    return render(request, 'todo/addNewTask.html' ,{ 'form':form})


def delete(request, id):
    #text_id = id
    Task.objects.filter(id=id).delete()
    global user_id
    user = User.objects.get(id=user_id)
    tasks_list = user.task_set.all()
    context = {
        'tasks_list':tasks_list,
        'username': user.username,
    }
    #return HttpResponse("text_id ={} ".format(id))
    return render(request, 'todo/index.html', context)





def edit(request, id):
    if request.method == 'POST':
        task_text = request.POST.get('task_text')
        due_date = request.POST.get('due_date')

        task = Task.objects.get(id=id)
        #task = Task(id=id, task_text=task_text, due_date=due_date)
        task.task_text = task_text
        task.due_date = due_date
        task.save()
      #  task.save(task_text=task_text, due_date=due_date)
        #task._do_update(task_text=task_text, due_date=due_date)
        #Task.objects.select_related().filter(user_id=task)

        global user_id
        user = User.objects.get(id=user_id)
        tasks_list = user.task_set.all()

        context = {
            'tasks_list': tasks_list,
            'username': user.username,
        }

        # return HttpResponseRedirect(reverse(request,'todo:index'))
        return render(request, 'todo/index.html', context)


    else:
        context ={'id':id}
        return render(request,'todo/editTask.html', context)



    return render(request, 'polls/editTask.html', {'id':id})


def start(request):
    return render(request, 'todo/start.html')

def index(request):
    return render(request, 'todo/index.html')



'''
def index(request):
    return render(request, 'todo/index.html')
    



'''

'''
def added(request):
    return render(request, 'todo/added.html')
    
    
    user_id = user.id
    context = {'user_id':user_id}
    
class TaskUpdate(UpdateView):
    model = Task
    fields = ['task_text','due_date']
    template_name_suffix = 'todo/editTask.html'


'''

webProj/todo/templates/todo/addNewTask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add new task</title>
</head>
<body>

    <form action="{% url 'todo:addtask' %}" method="post">
        {% csrf_token %}

        <h2>Add New Task</h2>
        <label for="id_task_text">Task: </label>
        <input type="text" id="id_task_text" name="task_text" value=" "/><br/>
        <br/>
        <label for="id_due_date">Due Date:</label>
        <input type="date" id="id_due_date" name="due_date" /><br/>

        <input type="submit" value="Add"/>


    </form>

</body>
</html>

webProj/todo/templates/todo/added.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>added</title>
</head>
<body>

    <h3>Tasks are added</h3>

</body>
</html>

webProj/todo/templates/todo/editTask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit task</title>
</head>
<body>



     {% if id %}

    <form action="{% url 'todo:edit' id %}" method="post">

        {% csrf_token %}



        <label for="id_task_text">Task &ensp;&ensp;</label>
        <input type="text" name="task_text" id="id_task_text" required/><br>
        <br>
        <label for="id_due_date">Due date &nbsp;</label>
        <input type="date" name="due_date" id="id_due_date" required/><br>
        <br>

        <input type="submit" value="Edit">

    </form>

    {% endif %}





</body>
</html>

webProj/todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}">

    <h4>welcome {{username}} </h4>

    <h2>My To do list</h2>

    {% if tasks_list %}

    <table>
      <tr>
        <th>Task List</th>
        <th>Due Date</th>
        <th>Delete task</th>
        <th>Edit task</th>
      </tr>

        {% for task in tasks_list %}

        <tr>
            <td>{{ task.task_text }}</td>
            <td>{{ task.due_date }}</td>
            <td><a href="{% url 'todo:delete' task.id %}">Delete</a></td>
            <td><a href="{% url 'todo:edit' task.id %}">Edit</a></td>
        </tr>

        {% endfor %}

    </table>

    {% else %}
        <h3>There is no task available</h3>
    {% endif %}
<!--

 {% if tasks_empty_list %}

    {% endif %}

-->





    <a href="{% url 'todo:addtask' %}"><button>Add New Task</button></a>


</body>
</html>





<!--

 <h2>My To do list</h2>
    {% if tasks_list %}
        {% for task in tasks_list %}
        <h5>{{ task.task_text }} : {{ task.due_date }}</h5>
        {% endfor %}

    {% else %}
        <h3>There is no task available</h3>
    {% endif %}

    {% if tasks_empty_list %}

    {% endif %}


-->

webProj/todo/templates/todo/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>

    <form action="{% url 'todo:login' %}" method="post">

        {% csrf_token %}

        <h3>Login</h3>

        <label for="id_user">Username &nbsp;</label>
        <input type="text" name="username" id="id_user" required/><br/>
        <br/>
        <label for="id_password">Password &ensp;</label>
        <input type="password" name="password" id="id_password" required/><br/>
        <br>

        <input type="submit" value="Login">
        <a href="{% url 'todo:signup' %}">Register</a>
    </form>

</body>
</html>

webProj/todo/templates/todo/redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SuccessFul</title>
</head>
<body>

<h3>You are successfully registered to our site</h3>
<h4>Now you can login to our site</h4>

<a href="{% url 'todo:login' %}">Go to login page</a>

</body>
</html>

webProj/todo/templates/todo/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>

    <form action="{% url 'todo:signup' %}" method="post" >
        {% csrf_token %}

        <h3>Sign Up</h3>

        <label for="id_user">Username &nbsp;</label>
        <input type="text" name="username" id="id_user" minlength="5" maxlength="15" required/><br/>
        <br>
        <label for="id_password">Password &ensp;</label>
        <input type="password" name="password" id="id_password" minlength="6" maxlength="12" required/><br/>

        <br>

        <input type="submit" value="Register">


    </form>

</body>
</html>

webProj/todo/templates/todo/start.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo appp</title>
</head>
<body>

<h1>Welcome to todo site</h1>
<br><br>
<br>
<h4>Here you can track all your todo lists</h4>
<br><br>

<h4>If you are the existing user please login from your account else press the sign up link</h4>

<a href="{% url 'todo:login' %}">Login</a>

<a href="{% url 'todo:signup' %}">Sign Up</a>

</body>
</html>